# Generated by Django 3.0.7 on 2020-06-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('D', 'Doll'), ('TD', 'Teddy Bear'), ('C', 'Car'), ('S', 'Shirt'), ('SW', 'SportWear'), ('OA', 'Overall')], default='D', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
