# Generated by Django 3.0.7 on 2020-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='mkfnsdf klsdmf sdfljs dsdkfjm skdfs dk slskdfs lk ksdm slkdjsfs ksldkfsldf dksmfls kdlsnf sdlk skldjfd'),
            preserve_default=False,
        ),
    ]
